changelog:
  exclude:
    labels:
      - skip-changelog
      - no-release-notes
      - dependencies
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
    - title: Chores
      labels:
        - chore
        - refactor
        - maintenance
    - title: Other Changes
      labels:
        - "*"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
template: |
  ## What's Changed

  $CHANGES
